website/form/urls.py
from django.conf.urls.defaults import patterns,include,url


urlpatterns = patterns('',
        (r'^contact/thankyou/$','form.views.thankyou'),
        (r'^gymkhana/thankyou/$','form.views.gym_thankyou'),
        (r'^contact/$','form.views.contact'),
        (r'^gymkhana/contact/$','form.views.gym_contact'),
)

website/urls.py
from django.conf.urls.defaults import patterns, include, url
import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
        url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
        url(r'^admin/', include(admin.site.urls)),
        (r'^comments/', include('django.contrib.comments.urls')),
        (r'^photologue/', include('photologue.urls')),
        (r'^pages/',include('pages.urls')),
        (r'^form/',include('form.urls')),
        (r'^issue/',include('issue.urls')),
        #(r'^yourvoice/',include('YourVoice.urls')),
        (r'^',include('videos.urls')),
        (r'^pressroom/',include('pressroom.urls')),
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT})
  )

website/form/models.py
from django.db import models

# Create your models here.

website/form/forms.py
from django import forms 

class ContactForm(forms.Form):
	subject=forms.CharField(max_length=100)
	sender=forms.CharField(max_length=100)
	message=forms.CharField(widget=forms.Textarea)
	

website/form/views.py
from django.shortcuts import render_to_response
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.template import RequestContext
from form.forms import ContactForm

def contact(request):
    errors=[]
    if request.method=='POST':
	    form=ContactForm(request.POST)
	    if form.is_valid():
		    subject=form.cleaned_data['subject']
		    sender=form.cleaned_data['sender']
		    message=form.cleaned_data['message']
		    recipients = ['editor.awaaz@gmail.com']
		    send_mail(subject,message,sender,recipients)
		    return HttpResponseRedirect('/awaaz/contact/thankyou/')
    else:
	    form=ContactForm()
    return render_to_response('awaaz/cnt.html',{
	    'form':form,
	    },context_instance=RequestContext(request))

def thankyou(request):
	return render_to_response('awaaz/thankyou.html')

def gym_contact(request):
    errors=[]
    if request.method=='POST':
	    form=ContactForm(request.POST)
	    if form.is_valid():
		    subject=form.cleaned_data['subject']
		    sender=form.cleaned_data['sender']
		    message=form.cleaned_data['message']
		    recipients = ['mehrotra.pulkit@gmail.com']
		    send_mail(subject,message,sender,recipients)
		    return HttpResponseRedirect('/awaaz/gymkhana/thankyou/')
    else:
	    form=ContactForm()
    return render_to_response('awaaz/gymcontact.html',{
	    'form':form,
	    },context_instance=RequestContext(request))

def gym_thankyou(request):
	return render_to_response('awaaz/gymkhana_thankyou.html')

def your_voice_form(request):
    errors=[]
    if request.method=='POST':
	    form=ContactForm(request.POST)
	    if form.is_valid():
		    subject=form.cleaned_data['subject']
		    sender=form.cleaned_data['sender']
		    message=form.cleaned_data['message']
		    recipients = ['editor.awaaz@gmail.com']
		    send_mail(subject,message,sender,recipients)
		    return HttpResponseRedirect('/awaaz/yourvoice/')
    else:
	    form=ContactForm()
    return render_to_response('awaaz/form.html',{
	    'form':form,
	    },context_instance=RequestContext(request))

def your_voice_thankyou(request):
	return render_to_response('awaaz/yourvoice_thankyou.html')

website/templates/form/form.html
<html>
<head>
	<title>Contact Me </title>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}/css/style
.css" />

</head>
<body>
<div id="wrapper">
<div id="main">
<h1>Contact Me </h1>
	{% if errors %}
		<ul> {% for error in errors %}
			<li> {{ error }} </li>
              {% endfor %}
        </ul>
	{% endif %}
	
	<form action="/contact/" method="POST">	
	{% csrf_token %}
	{{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.sender.errors }}
        <label for="id_sender">Your email address</label>
        {{ form.sender }}
		<br><br>
    </div>
    <div class="fieldWrapper">
        {{ form.subject.errors }}
        <label for="id_subject">E-mail subject</label>
        {{ form.subject }}
				<br><br>
    </div>

	<div class="fieldWrapper">
        {{ form.message.errors }}
        <label for="id_message">Your message</label>
        {{ form.message }}
		<br><br>
    </div>
		<input type="submit" value="Submit">
	</form>
</div>
</div>
	</body>
	</html> 	

website/templates/form/thankyou.html
<html>
<h1>thank you</h1>
</html>